#!/usr/bin/env bash
# Run the mdsip sandbox.
#
#   mdsip-sandbox.sh start [<tree-dir>]
#   mdsip-sandbox.sh stop
#   mdsip-sandbox.sh status
#
# A client of this server has arbitrary native code execution inside it --
# measured, see docs/security.md. Every flag below exists to bound what that
# code can reach. Dropping any of them silently removes a control, so they are
# grouped and commented rather than golfed into one line.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

NAME="${MDSIP_NAME:-fdp-mdsip}"
IMAGE="${MDSIP_IMAGE:-localhost/fdp-mdsip:latest}"
NETWORK="${MDSIP_NETWORK:-fdp-mdsip-net}"
TREES="${2:-${FDP_TREES:-/tmp/fdp-trees}}"

# Published only on loopback by default. The production deployment should
# instead put the origin and mdsip on the internal network and publish nothing.
PUBLISH="${MDSIP_PUBLISH:-127.0.0.1:8000}"

# These are capacity settings as much as security ones, and both failure
# directions are real: too high and the limit protects nothing, too low and
# legitimate load fails in ways that look like bugs rather than limits.
#
# The whole container shares one cgroup, so MEMORY is the total across every
# concurrent connection, not per client. A single \psirz read is a few MB, but
# a wide getMany over a large tree is not; 8g on a 200 GB origin bounds a
# runaway while leaving normal work room. Tune it against real load.
MEMORY="${MDSIP_MEMORY:-8g}"
CPUS="${MDSIP_CPUS:-8}"

# mdsip -m forks one process per connection, so PIDS is also a cap on
# CONCURRENT CONNECTIONS. Set it too low and clients get refused under load --
# a toksearch pipeline with 16 workers is 16 connections by itself.
PIDS="${MDSIP_PIDS:-512}"

# An allowlist seccomp profile, generated by tests/security/make_seccomp.py.
# podman's default is a denylist that permits most syscalls; this permits ~150
# and EPERMs the rest, which is what shrinks the kernel attack surface reachable
# from arbitrary code execution. MDSIP_SECCOMP=unconfined disables it for
# debugging -- and says so in the startup line, because a silently disabled
# control is the thing this whole file exists to avoid.
SECCOMP="${MDSIP_SECCOMP:-$ROOT/deploy/mdsip-seccomp.json}"

# Where the archive appears INSIDE the container. Defaults to /trees, but
# setting it to the host path makes the two identical, and then the tree path
# below is the site's real one with no substitution -- one less thing to get
# subtly wrong, since a bad path fails only at openTree, never at startup.
#   MDSIP_TREE_MOUNT=/mnt/beegfs/data/archives/mdsplus
TREE_MOUNT="${MDSIP_TREE_MOUNT:-/trees}"

# MDSplus resolves <treename>_path per tree, falling back to default_tree_path.
# Space-separated name=value pairs; paths are CONTAINER paths, so under
# $TREE_MOUNT.
TREE_ENV="${MDSIP_TREE_ENV:-efit01_path=$TREE_MOUNT default_tree_path=$TREE_MOUNT}"
TREE_ENV_FLAGS=()
for _kv in $TREE_ENV; do TREE_ENV_FLAGS+=(-e "$_kv"); done

# PTData shotfiles and the JSON index, both read-only. Empty disables ptdata,
# which is the right default for the tree-only fixture the tests use: a missing
# mount should look like "no ptdata configured", not like an archive that
# failed to appear.
#
#   MDSIP_PTDATA_ARCHIVE=/mnt/beegfs/data/archives/ptdata
#   MDSIP_PTDATA_INDEX=/mnt/beegfs/data/archives/index/json
PTDATA_ARCHIVE="${MDSIP_PTDATA_ARCHIVE:-}"
PTDATA_INDEX="${MDSIP_PTDATA_INDEX:-}"

PTDATA_FLAGS=()
if [ -n "$PTDATA_ARCHIVE" ]; then
  [ -d "$PTDATA_ARCHIVE" ] || { echo "no ptdata archive at $PTDATA_ARCHIVE"; exit 1; }
  # Nested under /fdp-archives to match what the INDEX records. Index entries
  # are absolute Pelican URLs that reach open(2) verbatim and resolve relative
  # to /, through the symlink chain the image builds:
  #   /pelican:/osg-htc.org:443/fdp-d3d -> /fdp-archives
  # so the shotfiles have to land at /fdp-archives/archives/ptdata or every
  # lookup fails as "file not found". Mounting only .../ptdata rather than
  # .../archives keeps the rest of the archive out of the sandbox.
  PTDATA_FLAGS+=(-v "$(readlink -f "$PTDATA_ARCHIVE"):/fdp-archives/archives/ptdata:ro")
fi
if [ -n "$PTDATA_INDEX" ]; then
  [ -d "$PTDATA_INDEX" ] || { echo "no ptdata index at $PTDATA_INDEX"; exit 1; }
  # No such constraint here: PTDATA_JSON_INDEX_DIR is a value we set ourselves
  # in the image, so the container path is ours to choose.
  PTDATA_FLAGS+=(-v "$(readlink -f "$PTDATA_INDEX"):/ptdata-index:ro")
fi
if [ -n "$PTDATA_ARCHIVE" ] && [ -z "$PTDATA_INDEX" ]; then
  # Resolution is index-only -- SYS_D3 is unset and a directory scan over the
  # archive is far too slow -- so shotfiles without an index resolve nothing.
  echo "WARNING: ptdata archive mounted but no index (MDSIP_PTDATA_INDEX)." >&2
  echo "         Resolution is index-only; every lookup will report as absent." >&2
fi

# podman derives several paths from /run/user/$UID, which does not survive the
# login session that created it. See docs/deployment-notes.md.
#
# The assignment is unconditional, not "${XDG_RUNTIME_DIR:-...}". The variable
# is typically still SET to /run/user/$UID after the directory is gone, and
# `:-` substitutes only when a variable is unset or empty -- never when it is
# set to something broken. So the old form detected the missing directory and
# then carefully preserved the value pointing at it, and podman failed with
# "the path in $XDG_RUNTIME_DIR must be writable by the user".
if [ ! -d "/run/user/$(id -u)" ]; then
  export XDG_RUNTIME_DIR="/tmp/xdg-$(id -u)"
  # libpod/tmp too: podman creates it under a runtime dir it set up itself, but
  # NOT under one handed to it, and then fails with "error creating temporary
  # file" plus a pause.pid path that does not exist. /tmp gets cleaned on this
  # host, so this recurs every time the directory disappears.
  mkdir -p "$XDG_RUNTIME_DIR/libpod/tmp" && chmod 700 "$XDG_RUNTIME_DIR"
fi

case "${1:-}" in
  stop)
    podman rm -f "$NAME" >/dev/null 2>&1 || true
    echo "stopped"
    exit 0
    ;;
  status)
    podman ps --filter "name=$NAME" --format '{{.Names}} {{.Status}} {{.Ports}}'
    exit 0
    ;;
  start) ;;
  *) echo "usage: $0 {start|stop|status} [tree-dir]"; exit 2 ;;
esac

[ -d "$TREES" ] || { echo "no tree directory at $TREES"; exit 1; }
TREES="$(readlink -f "$TREES")"

# Rootless podman maps container uid 0 to the INVOKING USER. Running this as the
# same account that runs the Pelican origin means becoming container-root is
# becoming the owner of issuer.jwk -- the one mapping that matters, and the one
# thing cap-drop/no-new-privileges are holding shut. A dedicated service account
# removes that path rather than defending it. See docs/security.md.
ORIGIN_UID="${MDSIP_ORIGIN_UID:-}"
if [ -n "$ORIGIN_UID" ] && [ "$(id -u)" = "$ORIGIN_UID" ]; then
  if [ -z "${MDSIP_ALLOW_ORIGIN_UID:-}" ]; then
    cat >&2 <<EOF
REFUSING TO START: running as uid $ORIGIN_UID, the same account that runs the
origin. Rootless podman maps container uid 0 to it, so container-root would be
the owner of the origin's issuer keys.

Fix it: run as a dedicated service account (see docs/security.md), or accept
the risk deliberately with MDSIP_ALLOW_ORIGIN_UID=1.
EOF
    exit 1
  fi
  echo "WARNING: running as the origin's uid $ORIGIN_UID -- container-root maps to it" >&2
fi

# A resource limit is only enforced if its cgroup controller is actually
# delegated, and podman will accept the flag either way -- on cgroups v1
# rootless it ignores all of them, announcing it in one line among its startup
# noise. So ask which controllers exist rather than inferring from the cgroup
# version: that covers v1 (typically none delegated) and the common v2 rootless
# case where systemd delegates memory and pids but NOT cpu.
CONTROLLERS="$(podman info --format '{{range .Host.CgroupControllers}}{{.}} {{end}}' 2>/dev/null || echo '')"
has_controller() { case " $CONTROLLERS " in *" $1 "*) return 0;; *) return 1;; esac; }

LIMIT_FLAGS=()
MISSING=""
if has_controller memory; then LIMIT_FLAGS+=(--memory "$MEMORY"); else MISSING="$MISSING memory"; fi
if has_controller pids;   then LIMIT_FLAGS+=(--pids-limit "$PIDS"); else MISSING="$MISSING pids"; fi
# cpu is the one most often left undelegated for rootless users. Its absence is
# a real but lesser problem -- a client can burn cores, but memory and pids are
# what bound the catastrophic cases -- so warn rather than refuse.
if has_controller cpu; then
  LIMIT_FLAGS+=(--cpus "$CPUS")
else
  echo "WARNING: no cpu controller delegated -- --cpus is not enforced." >&2
  echo "         A client can spin CPU; memory and pids are still bounded." >&2
  echo "         To fix: systemctl edit user@\$(id -u).service, Delegate=cpu" >&2
fi

if [ -n "$MISSING" ]; then
  if [ -z "${MDSIP_ALLOW_NO_LIMITS:-}" ]; then
    cat >&2 <<EOF
REFUSING TO START: these cgroup controllers are not delegated:$MISSING
podman accepts the corresponding flags and then ignores them, so the sandbox
would run without those limits. A client can call fork() -- see docs/security.md.

  host: cgroups $(podman info --format '{{.Host.CgroupsVersion}}' 2>/dev/null), \
rootless $(podman info --format '{{.Host.Security.Rootless}}' 2>/dev/null), \
controllers $CONTROLLERS

Fix it (best first):
  * delegate them (cgroups v2): systemctl edit user@\$(id -u).service, Delegate=memory pids cpu
  * run on a cgroups v2 host, or run podman rootful
  * accept the risk deliberately:  MDSIP_ALLOW_NO_LIMITS=1 $0 start
EOF
    exit 1
  fi
  echo "WARNING: no$MISSING limit enforced -- accepted via MDSIP_ALLOW_NO_LIMITS" >&2
fi

if [ "$SECCOMP" = "unconfined" ]; then
  echo "WARNING: seccomp DISABLED (MDSIP_SECCOMP=unconfined)" >&2
elif [ ! -f "$SECCOMP" ]; then
  echo "REFUSING TO START: no seccomp profile at $SECCOMP." >&2
  echo "  Generate it:  pixi run python tests/security/make_seccomp.py $SECCOMP" >&2
  echo "  Or accept the default denylist deliberately: MDSIP_SECCOMP=unconfined" >&2
  exit 1
fi

# An "internal" podman network has no route off the host. This is the control
# that turns code execution from a pivot into a dead end -- without it, a
# client can reach anything the origin host can reach, including the rest of
# the internal network and the internet.
if ! podman network exists "$NETWORK" 2>/dev/null; then
  podman network create --internal "$NETWORK" >/dev/null
fi

podman rm -f "$NAME" >/dev/null 2>&1 || true

podman run -d --name "$NAME" \
  --network "$NETWORK" \
  -p "$PUBLISH:8000" \
  \
  `# --- filesystem: nothing writable that survives, nothing readable that matters ---` \
  --read-only \
  --tmpfs /tmp:rw,noexec,nosuid,nodev,size=64m \
  -v "$TREES:$TREE_MOUNT:ro" \
  \
  `# PTData shotfiles and the JSON index, read-only, only when configured.` \
  `# Both are already inside the trust boundary: any token holder may read` \
  `# everything under /fdp-d3d/archives, so a client with code execution here` \
  `# gains nothing it could not fetch through the origin.` \
  "${PTDATA_FLAGS[@]}" \
  \
  `# On RHEL-family hosts podman mounts the HOST's subscription credentials at` \
  `# /run/secrets by default -- entitlement certs and rhsm config that nobody` \
  `# asked for and a client with code execution can read. Mask it with an empty` \
  `# tmpfs. Found by tests/security/verify_sandbox.py, not by reading docs.` \
  --tmpfs /run/secrets:rw,noexec,nosuid,nodev,size=1m \
  \
  `# --- privilege: no capabilities at all, and no way to regain any ---` \
  --cap-drop=ALL \
  --security-opt=no-new-privileges \
  --security-opt "seccomp=$SECCOMP" \
  \
  `# The sandbox connects to nothing, so it needs no resolver -- and an empty` \
  `# resolv.conf closes DNS as an exfiltration channel independently of what` \
  `# the network backend does. Worth doing unconditionally: even on an` \
  `# --internal CNI network the container is handed the host's nameserver, and` \
  `# only the missing route stops it being used. netavark's aardvark-dns sits` \
  `# on the bridge, which an internal network CAN reach.` \
  --dns=none \
  \
  `# --- resources: bound a fork bomb and a memory hog ---` \
  `# Only the limits whose controllers are actually delegated; see above.` \
  "${LIMIT_FLAGS[@]}" \
  \
  `# Where MDSplus looks for trees, INSIDE the container. The default suits the` \
  `# flat single-tree fixture the tests use; a real archive almost certainly` \
  `# needs its own layout, so override MDSIP_TREE_ENV with whatever the` \
  `# production MDSplus configuration already uses, rewritten to /trees.` \
  "${TREE_ENV_FLAGS[@]}" \
  \
  "$IMAGE" >/dev/null

echo "started $NAME on $PUBLISH -> 8000 (trees $TREES -> $TREE_MOUNT, read-only)"

# Print the identity mapping rather than leaving it to be inferred: the host uid
# behind container-root is what an escape would land on, and it is invisible
# from every other angle.
MAP="$(podman exec "$NAME" cat /proc/self/uid_map 2>/dev/null || true)"
if [ -n "$MAP" ]; then
  ROOT_HOST_UID="$(echo "$MAP" | awk '$1 == 0 {print $2; exit}')"
  SERVER_HOST_UID="$(echo "$MAP" | awk '$1 != 0 {print $2 + (5000 - $1); exit}')"
  echo "  running as host uid ${SERVER_HOST_UID:-?}; container-root maps to host uid ${ROOT_HOST_UID:-?}"
fi
echo "verify with: bash tests/security/verify_sandbox.sh"
